## Importing the required modules

In [ ]:
import numpy as np
import pandas as pd

In [2]:
import tensorflow as tf

In [3]:
tf.__version__

'2.14.0'

## Preprocessing the data


In [4]:
data=pd.read_csv("Churn.csv")
data.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [5]:
data.applymap(lambda x: isinstance(x, str)).sum()

customerID          7043
gender              7043
SeniorCitizen          0
Partner             7043
Dependents          7043
tenure                 0
PhoneService        7043
MultipleLines       7043
InternetService     7043
OnlineSecurity      7043
OnlineBackup        7043
DeviceProtection    7043
TechSupport         7043
StreamingTV         7043
StreamingMovies     7043
Contract            7043
PaperlessBilling    7043
PaymentMethod       7043
MonthlyCharges         0
TotalCharges        7043
Churn               7043
dtype: int64

In [6]:
print(data)

      customerID  gender  SeniorCitizen Partner Dependents  tenure  \
0     7590-VHVEG  Female              0     Yes         No       1   
1     5575-GNVDE    Male              0      No         No      34   
2     3668-QPYBK    Male              0      No         No       2   
3     7795-CFOCW    Male              0      No         No      45   
4     9237-HQITU  Female              0      No         No       2   
...          ...     ...            ...     ...        ...     ...   
7038  6840-RESVB    Male              0     Yes        Yes      24   
7039  2234-XADUH  Female              0     Yes        Yes      72   
7040  4801-JZAZL  Female              0     Yes        Yes      11   
7041  8361-LTMKD    Male              1     Yes         No       4   
7042  3186-AJIEK    Male              0      No         No      66   

     PhoneService     MultipleLines InternetService OnlineSecurity  ...  \
0              No  No phone service             DSL             No  ...   
1        

In [7]:
    x=data.iloc[:, 1:20].values
    y=data.iloc[:,20].values

In [8]:
print(x)

[['Female' 0 'Yes' ... 'Electronic check' 29.85 '29.85']
 ['Male' 0 'No' ... 'Mailed check' 56.95 '1889.5']
 ['Male' 0 'No' ... 'Mailed check' 53.85 '108.15']
 ...
 ['Female' 0 'Yes' ... 'Electronic check' 29.6 '346.45']
 ['Male' 1 'Yes' ... 'Mailed check' 74.4 '306.6']
 ['Male' 0 'No' ... 'Bank transfer (automatic)' 105.65 '6844.5']]


In [9]:
print(y)

['No' 'No' 'Yes' ... 'No' 'Yes' 'No']


In [10]:
from sklearn.preprocessing import LabelEncoder
l = LabelEncoder()

In [11]:
list=[0,2,3,5,6,7,8,9,10,11,12,13,14,15,16,18]
for i in list:
    x[:,i]=l.fit_transform(x[:,i])

In [13]:
print(x)

[[0 0 1 ... 2 29.85 2505]
 [1 0 0 ... 3 56.95 1466]
 [1 0 0 ... 3 53.85 157]
 ...
 [0 0 1 ... 2 29.6 2994]
 [1 1 1 ... 3 74.4 2660]
 [1 0 0 ... 0 105.65 5407]]


In [14]:
y[:]=l.fit_transform(y[:])

In [15]:
print(y)

[0 0 1 ... 0 1 0]


In [16]:
np.argwhere(np.vectorize(isinstance)(x, str))

array([], shape=(0, 2), dtype=int64)

In [17]:
x=x.astype(np.float32)
y=y.astype(np.float32)

In [18]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [19]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [20]:
x_train.astype(np.float32)
y_train.astype(np.float32)

array([0., 0., 0., ..., 0., 1., 0.], dtype=float32)

## Training the ANN Model

In [21]:
ann = tf.keras.models.Sequential()

In [22]:
ann.add(tf.keras.layers.Dense(units=12, activation='relu'))

In [23]:
ann.add(tf.keras.layers.Dense(units=12, activation='relu'))

In [24]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [25]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [26]:
ann.fit(x_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
177/177 [==============================] - 2s 3ms/step - loss: 0.5371 - accuracy: 0.7341
Epoch 2/100
177/177 [==============================] - 0s 3ms/step - loss: 0.4471 - accuracy: 0.7829
Epoch 3/100
177/177 [==============================] - 1s 3ms/step - loss: 0.4305 - accuracy: 0.7914
Epoch 4/100
177/177 [==============================] - 1s 3ms/step - loss: 0.4233 - accuracy: 0.7973
Epoch 5/100
177/177 [==============================] - 1s 3ms/step - loss: 0.4183 - accuracy: 0.7977
Epoch 6/100
177/177 [==============================] - 0s 3ms/step - loss: 0.4148 - accuracy: 0.7996
Epoch 7/100
177/177 [==============================] - 1s 3ms/step - loss: 0.4116 - accuracy: 0.8012
Epoch 8/100
177/177 [==============================] - 0s 3ms/step - loss: 0.4089 - accuracy: 0.8048
Epoch 9/100
177/177 [==============================] - 0s 3ms/step - loss: 0.4072 - accuracy: 0.8071
Epoch 10/100
177/177 [==============================] - 0s 3ms/step - loss: 0.4056 - accura

177/177 [==============================] - 0s 1ms/step - loss: 0.3766 - accuracy: 0.8248
Epoch 82/100
177/177 [==============================] - 0s 1ms/step - loss: 0.3764 - accuracy: 0.8227
Epoch 83/100
177/177 [==============================] - 0s 1ms/step - loss: 0.3767 - accuracy: 0.8211
Epoch 84/100
177/177 [==============================] - 0s 1ms/step - loss: 0.3761 - accuracy: 0.8230
Epoch 85/100
177/177 [==============================] - 0s 1ms/step - loss: 0.3776 - accuracy: 0.8227
Epoch 86/100
177/177 [==============================] - 0s 1ms/step - loss: 0.3765 - accuracy: 0.8246
Epoch 87/100
177/177 [==============================] - 0s 1ms/step - loss: 0.3758 - accuracy: 0.8239
Epoch 88/100
177/177 [==============================] - 0s 1ms/step - loss: 0.3755 - accuracy: 0.8245
Epoch 89/100
177/177 [==============================] - 0s 1ms/step - loss: 0.3747 - accuracy: 0.8259
Epoch 90/100
177/177 [==============================] - 0s 1ms/step - loss: 0.3758 - accuracy: 

## Checking accuracy with test data

In [34]:
from sklearn.metrics import confusion_matrix, accuracy_score
pred=ann.predict(x_test)
pred=(pred>0.5)
accuracy_score(y_test, pred)

45/45 [==============================] - 0s 991us/step


0.7906316536550745