In [89]:
import numpy as np
import pandas as pd

In [90]:
import tensorflow as tf

In [91]:
tf.__version__

'2.14.0'

In [92]:
data=pd.read_csv("Churn.csv")
data.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [93]:
data.applymap(lambda x: isinstance(x, str)).sum()

customerID          7043
gender              7043
SeniorCitizen          0
Partner             7043
Dependents          7043
tenure                 0
PhoneService        7043
MultipleLines       7043
InternetService     7043
OnlineSecurity      7043
OnlineBackup        7043
DeviceProtection    7043
TechSupport         7043
StreamingTV         7043
StreamingMovies     7043
Contract            7043
PaperlessBilling    7043
PaymentMethod       7043
MonthlyCharges         0
TotalCharges        7043
Churn               7043
dtype: int64

In [94]:
print(data)

      customerID  gender  SeniorCitizen Partner Dependents  tenure  \
0     7590-VHVEG  Female              0     Yes         No       1   
1     5575-GNVDE    Male              0      No         No      34   
2     3668-QPYBK    Male              0      No         No       2   
3     7795-CFOCW    Male              0      No         No      45   
4     9237-HQITU  Female              0      No         No       2   
...          ...     ...            ...     ...        ...     ...   
7038  6840-RESVB    Male              0     Yes        Yes      24   
7039  2234-XADUH  Female              0     Yes        Yes      72   
7040  4801-JZAZL  Female              0     Yes        Yes      11   
7041  8361-LTMKD    Male              1     Yes         No       4   
7042  3186-AJIEK    Male              0      No         No      66   

     PhoneService     MultipleLines InternetService OnlineSecurity  ...  \
0              No  No phone service             DSL             No  ...   
1        

In [96]:
print(x)

[['Female' 0 'Yes' ... 'Electronic check' 29.85 '29.85']
 ['Male' 0 'No' ... 'Mailed check' 56.95 '1889.5']
 ['Male' 0 'No' ... 'Mailed check' 53.85 '108.15']
 ...
 ['Female' 0 'Yes' ... 'Electronic check' 29.6 '346.45']
 ['Male' 1 'Yes' ... 'Mailed check' 74.4 '306.6']
 ['Male' 0 'No' ... 'Bank transfer (automatic)' 105.65 '6844.5']]


In [97]:
from sklearn.preprocessing import LabelEncoder
l = LabelEncoder()

In [98]:
list=[0,2,3,5,6,7,8,9,10,11,12,13,14,15,16,18]
for i in list:
    x[:,i]=l.fit_transform(x[:,i])

In [99]:
print(x[0:6,17])

[29.85 56.95 53.85 42.3 70.7 99.65]


In [100]:
print(x)

[[0 0 1 ... 2 29.85 2505]
 [1 0 0 ... 3 56.95 1466]
 [1 0 0 ... 3 53.85 157]
 ...
 [0 0 1 ... 2 29.6 2994]
 [1 1 1 ... 3 74.4 2660]
 [1 0 0 ... 0 105.65 5407]]


In [101]:
y=data.iloc[:,20].values
y[:]=l.fit_transform(y[:])

In [102]:
print(y)

[0 0 1 ... 0 1 0]


In [103]:
np.argwhere(np.vectorize(isinstance)(x, str))

array([], shape=(0, 2), dtype=int64)

In [104]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [105]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [106]:
ann = tf.keras.models.Sequential()

In [107]:
ann.add(tf.keras.layers.Dense(units=12, activation='relu'))

In [108]:
ann.add(tf.keras.layers.Dense(units=12, activation='relu'))

In [109]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [110]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [112]:
ann.fit(x_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100


177/177 [==============================] - 4s 6ms/step - loss: 0.5112 - accuracy: 0.7410
Epoch 2/100
177/177 [==============================] - 1s 7ms/step - loss: 0.4524 - accuracy: 0.7737
Epoch 3/100
177/177 [==============================] - 1s 6ms/step - loss: 0.4394 - accuracy: 0.7794
Epoch 4/100
177/177 [==============================] - 1s 6ms/step - loss: 0.4311 - accuracy: 0.7847
Epoch 5/100
177/177 [==============================] - 1s 6ms/step - loss: 0.4252 - accuracy: 0.7897
Epoch 6/100
177/177 [==============================] - 1s 6ms/step - loss: 0.4212 - accuracy: 0.7939
Epoch 7/100
177/177 [==============================] - 1s 6ms/step - loss: 0.4175 - accuracy: 0.7961
Epoch 8/100
177/177 [==============================] - 1s 7ms/step - loss: 0.4149 - accuracy: 0.7987
Epoch 9/100
177/177 [==============================] - 1s 6ms/step - loss: 0.4122 - accuracy: 0.7998
Epoch 10/100
177/177 [==============================] - 1s 6ms/step - loss: 0.4102 - accuracy: 0.8037
E